export type TaskStatus = "upcoming" | "in-progress" | "completed";

export type SubtaskStatus = "pending" | "in-progress" | "completed";

/**
 * Data generated by the planner/AI.
 * The planner does not own IDs, status, or timestamps.
 */
export type GeneratedSubtask = {
  title: string;
  description: string;
  durationMinutes: number;
  deadline?: string;
};

export type GeneratedTaskPlan = {
  summary: string;
  subtasks: GeneratedSubtask[];
};

/**
 * Application-owned representation of a generated plan.
 * IDs, status, and timestamps are assigned by the app.
 */
export type Subtask = GeneratedSubtask & {
  id: string;
  status: SubtaskStatus;
  completedAt?: string;
};

export type TaskPlan = {
  summary: string;
  generatedAt: string;
  subtasks: Subtask[];
};

export type Task = {
  id: string;

  // Original user input — the source of truth.
  title: string;
  description?: string;

  // Scheduling/application data.
  createdAt: string;
  scheduledDate: string;
  startTime: string;
  durationMinutes: number;

  status: TaskStatus;

  // AI-derived data.
  plan?: TaskPlan;

  completedAt?: string;
};
